; generated by SuperSlicer 2.3.57 on 2022-07-01 at 23:30:42 UTC


;
; thumbnail begin 16x16 976
; iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACoklEQVR4AT1TWUsbURSeH+aT+CAICo
; L4ID6IgiiiQlRcSEAhUSJBiUkMZk+aTPZJJpkkk5nEJNOkbol32tqFtrTQQhdK6UN/QO93YTJwucs5
; 5zvfOecbLhAIqPl8XojFYlWPx9OKRCIyVq1WS2LBpihKIhQK1eHrcrk6hUIhDx/cuXg8LmWz2aLX67
; 3GGY44S5KUabVa0XQ6LSIA4EaiZDJZxh07BxSfz9fAXiqVsggGYKVSSdevrhTeZHoS6AcQgCIwGAwq
; SAZADsEIAAAMxWIxJ8tyUnE4NH1m5lt/aupH6exMo4YsSgJDgCHO7Xa3uXA4zGoGHVVV44Lfr9xNTv
; 7Ux8d/k/39Pjk6utVHR//eLC5+FGnWRqMRN5jyPC9xQCyXyxnQVO32LrISk+klWVl5RxYWPrH7xsZr
; src36NNzx2p9IYoiYwMmHIJlWkzLbO7DWZ+Y+EW2twlZX38i8/OfydzcF3ZfXn5P1tbeYNcslgfEgA
; knRKPV++np76BJDg76xGrt4cxKsNs1YjY/6GNjf/SRkX/k5KRLdnYI7I80kejxNLm409nu2Ww91Ips
; LNBiuWdA1IkBoxd0wcZK2t197FJ74uKizVEaGaqaZP3yskE2N1+xeldX3zLqoI1l3JeWPmCpp6capo
; BRc2gexpZIJCQ5lxPuKDKZnf3K6gerrS2dMaFrcHh4y9tsN1QDlWETMUKoC81kc6bIPb9fHvYCJVCg
; 6+PjXvj8vAPN0IQ8YoZSxkwh2VQqVYLawEigmQZoGm2i4vWqVC91+vFQnyFlgDApG3LGI0ZTrVZToK
; fSefscjue5XK4AYNjgA+2A+VDKOOARRtzBCCBGRuxIYvjgDX5Op1PjQMP4A1EGSoITMjabzWegizPs
; YAW78etDyv8B0yKYhFYJMOQAAAAASUVORK5CYII=
; thumbnail end
;

;
; thumbnail begin 220x220 14744
; iVBORw0KGgoAAAANSUhEUgAAANwAAADcCAYAAAAbWs+BAAAq+UlEQVR4Ae1d+6+eVZV+/5UxCl4jEM
; WYYCKRBC/EaPGCRKjBHItN0VraUoXjaYttoS3Q0uuhp+3UTmMpnXIpl6GUuygg1RYtCA6hpmRgDMmQ
; CRmT4YdO1xkWWW72Zd32e77vnP3DCnp6zre+/e5n73ev9Txrr+688847FbOLLrro7SVLlhzfuHHjE1
; dfffVL559//jup303ZlVdeeeKyyy57g/O7s2bNegt+X+PnqquuegW+5/XXX3/kwgsv/Hvsd+Bz4fdu
; vvnm38DvoknHBs8F/iblJ/QpeQahHxgPfEf43iU/ODb4G/hbqT/4jiU/9LvBuKR+cJ6o5XwOEwbh+5
; UwCNZJJvLb3/72m9wJ4YIyBlCJnxtvvPFZDijpQ8W/QeOO7YorrngNvp9kTOhTAhjwA98Lnjv3WdCx
; wd/BZ3D9wbODv9XMFQfMdJ7Q4DtyfFowCItVunhwXNzNhI6Ng43OeyLh38EkgwwNJhGs5EcyceFDxR
; 2JAiA1Nukk5ICTAwz8Du7oP//5z49pdlo6NviM3KaHbyrtmBAbMK6UH5yn8FSh8TNoGIRnB+OB78XF
; BmvBUcDgRIYO8N8toAzBEJtI8INHLc3EhQ81PGKGIMVjhseY0Gfs2AJ+8LtYwULHBhZ7C2mPuilshC
; cT+Bk8y3CxWXyGGIxhow8M0uO+FIOd5JcpMHCnwcnlHuk0E4mTBP/1mLjw4eFbJXzbeYIy9EnfmJwY
; 1Do2PNJqj/tcbMC4Zs+e/Xq40DzHNhUYxM2EvrE12BAvOPwSOJEbNmx4ogYowwe8fv36X9cAJY6HJl
; Q2b9782L59++5ZuXLlc5pjHdfnokWLXuQkD7zGBjY6Ovp8DT9ogIs9e/bcB88Qx+Z5QpgqDMKCQ3xY
; MKhacGD4WoWFIA3upX7gjAwTCMeIWn7AYGHjgqNvuxo+caeE51frjYOGcZ0moSKdJ01ixOITMIGbSR
; 8YhEVu8aNacLBj4as8TF97TiQGpTTVnYqBrIZvAkwCxNLXHj5pbIPnf2l2VmI0Bi3FQNZ5Cp9XKgby
; 8olvtZoYpMd9xCDMk3bTEi241PnfgwcK/eQ4KC0PlLLY+T9FH1h8lmJQCw9UAmXoJ4yBrPNE32rUp/
; dmUsKgxzxxMQjPTuqHveDgw0txhpYHCv1wjnIWUplaLlVP44QwoSL1wyVGPSgITmLESkHE0v25seHJ
; wbKZcHjQEINaP7UwWFxw9KjF+UAJD+QBgBIPVAIlxw9MQIk+yPmREKNoHB4o9V0lQMOxcWOg2CbEpT
; K0bzvpJhRiqQ8McuPwrgQWbYapxAOFX9jCQUknksagXEsdn3I+YzGo1Cd3M7FwUNwYCH4v3Hg0Y5PE
; QBYelG4mg4LB5IKDB289rnG0cJ7n7lIMZOWgUnrMEKSl87/3RHpwUKUYSKqD5GCjFAN5hAwhSV3CoD
; XBU8JgFw7ImxhNaeE0OkgJQMOJ5MSgkoeaSqhodZAcn7G3T0kuph0bxkCaN7t0rvrGIIZHU4HBjsZA
; WnGudCIXL178Qm2eBmMgGJdGnMt5qKEec+/evffu3r37gaVLlx6tQZjTt50kBtX4gZMJjGX//v13h7
; Grt08aA3noIDkYXLhw4Z/7xCAuwMkjJfwAVBW1BooGfiYmJg4DMGGwNcleHPCKFSuO1PRD9Zh33XXX
; AQCpJ8cVM1CLaJTwXKMLDsYkSYxYsHHDDTc82wcGd+zY8RCoYfrAIIxn9erVz6Cfjgal3jwQNcpBjY
; yMnPTggXKGMWhNUhn94E4ZKlS85Ub0qKXlgUoGz4m+0bZu3foobii13qg0Bu0Lg3Pnzn21NgbxuEyP
; zl0IRA8eKLQYB2XlgTigpD/34IFCP/T871XgmrJYDOrFRYbzFEsIxWIgD4vFoH1hkCb1+sJgMkup5Y
; FSoEzFhlIeqATKXAwKY4Hf8fCTOv9bClxT37kUg0p4oNI85XSQHsKGEJS5z+gDg7i4PTGYe2MWeTit
; Fk7CQVm1cNIdUauFi+kgU78XptE1IJXwoNqjc0wHWRqbRtgQ+uQe4/rCIGwm8HswT1oMcnhQltJEeu
; 2BhoMq8UC5B6XJrEpjIE0tHiVTaZaP41PLg3JjoFi6XzI2KmyQLB7L1Rvc79Y3BiU8KFtLyZlIetTS
; xhUSLZw1GcKdSK4OMuVDosf04KBKb3ypDjJlNAYqZU09eFApBrXYkGBQyoOKqgVSMRA9Zniw9SUtnD
; cHlYqBtDrIFBBibzs6Bm8eNIyBYtyhdWw0oQLPKoYNTx40h0HEDGDQio1aGFTVw9EYiILSO70a08Jp
; dJDcB0zfmFYdZMxy5SzeWTnqE3dh73IjarEYyKLF5WAQNxPv+2BSGKTY0PoxV3wD9+Q5cTk/4+Pjj9
; TyQx8wkPPS8z/XwoTKtm3bHgYS1rtwkhrsxOBj+/bthz10kJyxwbUHNXyE2Di9iTzTJwZhbBY/nfUL
; wGu39n0SsAjATw0eKPSDbx3wV3Nxx65z8AZN+EZFXzXnC+O6NWvWPF2TVA6vPaiNQXirUQxq50m84G
; JBqZUHyhk9/3vyQNRSMagHD5QCCz4vyf2YmnkKY0bU9dW6p4Ve56CpSZNikGKjhhImjEGtGBTdS5lj
; 5bU8UA6UKaLSygOFfnIxqIUHSoEl9MO5H1MzT9RCnzQGso4plxX1FDaUeFBcHIOMQdaCo1eElY4IHl
; o4TqpeUuCaMi7n4iGhwklKTQ7eQBVLqHB9xHi/XNYYAWXZTDg8qFXYgPPN5QoBr1YMcnhQDQY7juPS
; xKUAKj3nSjkoCQ+UAwD3+2k3Ey4xatFjagtELZuJ5EQT6jEl2NBQTrQkRjImCwY589TlPshanCeJgb
; QcVIkHivmxEKPSo7OGg5LoMbk6SI5Pbgxk4UElMZCVB0XOjruZeGCwpJvtYisZOSj4AGvWrBQDad+G
; sYlEHij2FirFoFIrxUBWDoqjx/RqlBH6zAHGo0CUEwN58qCli6Y8MZjbTOD/d/T8CV/Iq1FGbEDhTq
; PVQXJASjWLtYjR1GZijfeo0fgZDSrKvRtlhD7DTYsrzpVYLAbSHvcHFYM04w0/63DXh8po74kLjcZA
; nqCM+aF36UvP/9qJlJ7/uQafh/O0a9euBx944IHbt9500284iRGLT9z1JeJcqdEYaNmyZX/QJIssGK
; xVmEwxODY2dhTnqQPHW7ZsmWxe4f0GSH2RDRs2PNmHH7jKAQAK46pdSg+ggSsCaqlF4HPXrl3720O3
; 3fbQcxdc8F+/+dzn3t65dOnkEbqmT7geoLZiBOZmKjBYa7FRP4hBnKcOg9IFCxa8nIuBPIye/2uRym
; A0BoU3jhcPFDN6/vfmgdAweXDnyMgrxz7ykVNoR8466x34WY2x0Ri0FAN5jA3ma968ea/UbDgyFRiE
; NUW7F3U0KE3FQB6gjJ3/vUnlVAzqwQPFLHX+9+CB6MTB8fGRL3/5TbrYqD1xwQVvTaxa9azX2GLH/R
; phQIwHTcVAw4LBVAyKP+9SQPK6YKV0/veayBIxauGBuKCkpuWBwgna/dOfHoM3WWqx0bfdr66++rhl
; bJwY1EPYwEmMDCMGS/Wgk0fK3JewauEkxyuLFk5CjFq1cBjkc68fl/BA4cTdf8klr5UWWmjwN7cqrp
; uTcFAIUI2IXMKDelA5Eh5Ui8GUFjdmRaWJRgunJUalMZCWGNVq4bQcFDcGQoBBMgSSItLFhoYJFc7Y
; LByUJAayLB4tBi0ktgaDHGx03A/lxkAeBaKcGIirgywBhqOF8+CgSscWPEKFiRGtYUIF3nYp8HhwUJ
; wYyIMHlWLQI0SpgUFRtUAuBvLmoFIxkDcxWtLCeXNQsRgIPh8SI5D88FhssYRKODbPBEhuM9FocUsY
; TIHcG4P4lvTEoLgeLhYDaTVonAdMYyCrDrI0kaEWrkaKnwJ09uzZr4O/O+bNe8l7oYVvO/ABvi699N
; K/cWNQDTZwYXtocQcFg3QzsWKw034JjIGgKXxtApFev12jmUQ4kTAmKN2vSZbDxAEhevjii1+vudio
; ga89t912uBbHhdgAgh6ujtCIqDUYBOsDg1gxb8Gg6U4TSirXlmn1VUoPu/G11177R28eiAIFPheSGs
; +ce+7f+1psNKEC9EGNsVEeFOaqloCCYoOSyn1h0LK4VQuOFueVYiAr+MPzvwcPFLPw/O/JA6EhV3jP
; 5Zef6HuhhUdM+A6QUPECaYwHTcVAHkaPebR4d9AxKFpwqaA0FQNZwJ87/1t4oJilzv8ePBAaPDdrut
; /bIKEC38na+irHQXkrVFI86FRhULqZsBcch4PyuOQndkFMyqxaOG6633IvR0oHOSiG9AGneDcHylLC
; wuOiqb4wSLW43hhk9xbgrmStFg5jG2ktnlYLJyVGNXpM1EEe+vrX3xjExRa+7TYvW3aEe1TScFDakh
; gpD2rBoKYeVILB7IJDAlrycNAkMVBJB8mdSO7f0hhUM/EloOHinKrEiOVthwmV0tgs6X5JDGThQbF4
; t08MljaTLgdKj2vNSjGQZ0+CkhbOixjNHVssOshBsZQe05MH5ZycPDBIi3f7wmBuM+nC86dWB5mzWA
; yk1UFyJzKcKI+7OEI/VI+Jz23QEiNao3pMmon25kFjMZA3BhETfWIw1nAEftbR86eHDjJl9CiyatWq
; 31l1kCXD47C1TIYDmE2bNj0OzefvnjPnL8O0qEoGR0wY07379t29c+fOQzWx0QcG8aIpeqVIbQwCPm
; BcGIN2OGAope+jtH3Hjh0PQdk5DLbWQNFg8lauXPlcTT/wIHds3Pj4by+++D+GaTFJ7NmLLvrPf16z
; RtUZVIKNPjEIzU36wCA8M7h6A4+qHQ1KvRvPU6Pn/5GRkZPchneWgcIO480DoUkLRKfD2w71mN4gpT
; xoLWHDoGCwC3kGbeo2ZTRxQoNSjwLX1EKInf89eKBw4oY5MaI1oDgwoWJdFKl0fyoG8sAgjUGnAoPJ
; LKW28XzouFQHpbmfPWWl8791M6EFosOU7vc2Dz0mhwf1aDjCqcWzCBukGOxKD+UKQeN5ahJilCZUNN
; kpbPvEnXzNscW7QHTYjRa4SjdKCQ+KGNRe8aHBoCas4lJObKWJ5AFpiFGtFk5LjEoUNDULRIfdUgWu
; FlB6YFBTi1cqsk4ZbAhcP2wtJScG8iBGJVo4yQUxuQWbOrbgxNUuEB12w7ddbqP0KBDlXPIj0eJaMY
; gLVOJHVC2QioE4ihKpn9wlP1IdZMliWjgUsA6DDnJQDN52YUJFcpKwYlCjxe0bg6p6OBoD0Wps7/Rq
; TAun1UFyJxL8DKMOclCM6jHxIh7vuQoxaNVB5iyW1LNgUF3xDQPFKthajTLAUAsHfoCwrElUwkPcvn
; 374YfmzHl5mEA+iPbw5Zef2L5hQ9U+AX1hEKVt4Gd8fPwRCwY77RfAoBSvPailQACDnQz8eKVuYzad
; dJCDYlSPWaNCf6owaClw7TSOYZAwWFzp2pq0koXnf6qF81LEDHqB6LBbjYYjsWaNfWLQUuDKXnAhV5
; b6Yl5n6NQlpdyaNI5huj/XKKOZj3k0HClRTlOBQWnTG9aCo61tS4Px0MJxHlq402gmbqboIAfFLHrM
; UqOMGhgsvZE1F01lFxxNjUqCUq0WLnVBTM6PVAs3k3WQg2JUj8mZYy0GNTI+aS2elBLrco4lTQpiJt
; HCWQpEOVq4poMcLIOECpwwchulBwYll/xYavG4eswu9mr3ipHwoWEhaGohSC6IyflJJVSaDnIwLafH
; 9MZgLqEi1eJqMIj/3tHzp1YHWbJUMOvdKCOmhWs6yME3qscMM9HTAYPwcwxlOjx/4rUHtXguMKqFq9
; UoA/2sW7fuKbj24M75818YJvDNVIO33cG5c1+GOQNyuS8M1up9QPtUjI2NHcW3dYds/b59++6pIY2J
; fRG49qCmH9hNQBXw1He/e2KqgdRMZnCdw8bVq5/2KHAtYbB2AxDwA1c5QNMWWGNwZO2wOG/u3Lmvep
; PKodFXeo1SehSwtsTIcBvMXa2GI1QHyWm6aPGDbzV6Y1gXXnugqQcqWaoOyvNGrUFplNHMx+CIqe1X
; LsGgd8ORVB4EKa8oLeBxPztaqQ4K1d4WLVzTQU5fw4YjFj0mB4MeCpVSPSj46XJfQtN4PhwEd+fQaO
; GaDnJmmFaPKcUg3lqnwTqX/C5KuzSX/OAXl3xp6U4zTI0ymvmYRI+Z0kFyMchd2FizySXnWVpKSdNF
; j1dzLqEyrI0ymvkYFrjmcgy1MYimkZyxqwVKl/xoL4iR7DRNB9kMLZZQkWpxuRgMF7alJ4G4Hi6WUP
; FulEENdir47EWLFr3YEiPNqNEC1zlz5vy1JgYxqUebNWoym6qKb1oPVFMVgLsJqEYOzZ9/fJjA0Kwf
; gyMmYGP85pufqolD+OyJiYnD1kuK1HeaoAZNWg8ksVYg2oxrHgWuOazDQgP1Eiw2y8JWLTiqg5TWA3
; GsFYg205h3w5FULZ5FJSVacLniPK/72VtipJnVPBqOlBIj2iJr9oLjFOdZ7mdvBaLNPM3ScERSiydt
; OFJccNJ0v+aSHyQPmw6ymadJG45o60ElTW+yC07SpCA0rh4TFjMEuy3d36yWcRqOWPticFVSXe4tZS
; 3Oy+kxW6OMZn1aquGId9Kv1HCkC7Mt3o0ywEI9ZmuU0WyqjDYckeogpW+78E0JP+toPVCtRhm4kKG5
; +OS1B7fc8kRLjDSbKoO33T2jo0cOHDhw502ned5aPQmQPqCt3jr8h9WrVz9Tq9MJvuWAOHz8+9//92
; GanGbT1wCLXgWuKYM1tXz58t9jQqWjxXmejefp67UViDYbVKvVcCQUPqMe8333UkrrgUrHyFYg2mzQ
; jdIHXriPnRYn76VM/ZH1kp+mg2w2bOahxyzlQYq9BaQXrDQdZLNhNq0ekysQYUm7uJf8NB1ks+liEj
; 2mpB5U1B8udcFK00E2m45W0mNqToCiaoFYQqU1ymg2nS2lx4Q1oKHRVPVwmFCZP3/+X1qjjGYzwage
; E3DfW49vPF6uWbPm6XsXLfrjMD20Zs0shtc5WPoSiBccJkaaDrLZTDWqx5TSB6Jr8lqjjGbN/t/wfk
; xpgSubFmiNMpo1e79JG44UF1zTQTZrljeJHrPLJUaaDrJZM55xG45EFxw2ymg6yGbNZFbSY/5DtQBt
; lNF0kM2a6SzVcGSyWgAv+RkZGTnZdJDNmvkZTaggndZBk4z9+/fffcf4+OGWGGnWzNdgTe3euvUwXO
; ewdOnSo5NvuF27dj24d9u2QzsuuODNp888c6gG1KzZoNrvPvzhU5s+9am39/7yl/fDGoO11sFrDhsV
; XH/ddcfWf+1rr93/sY+1+K1ZM4M9+MEPnlr51a++Bpn+9evX/xrXWUcvv8T7KNfMn3/8Xz75yb8/d3
; qFDtMgmzUbBNt+xhnvrFm48Bi9Kwj7FHQxsg5+4YZly45smzXrtUOnV+owDbZZs6myRz/0oVOrv/jF
; N2Bxxe4KAhFJl9NOwttu0+LFx+7+6EffaW+7Zs3S9qt/+qdTK0dGXio1ayxKuyYLTE8TeS2h0qzZ+w
; 0SI7ecc87bt/ziF6yGISzxMl6hsOF733sF3nbD9ECaNatl//qBD5xa/s1vnqDNGl0WHBqQd2uXLDk2
; 8elPv92OmM1msm07vQZuuu66I9Jbm8UFqJPyr3fpg5ZQaTbTDBIja09jX9vWWHXFAqUP7jjnnP9pb7
; tmM8F2n3nmO5AY0fZMVC84PF6CY6APxr/whTefPOOMoXp4zZpxDd5qN5599ttrly17ztphSrzgwmaN
; yC+0hEqz6WiQ7v/FZZe9QvlqS9Mb0YLLNWuEVY8JlUYfNBt2g3R/LjGibXrDXnCcVyksyCU/+clLkF
; B56OMfb2+7ZkNpNDFSeotJm94UFxy3SUF45ISEyu1nndX0mM2GykAHeeNVVx2XJEYkV55nFxxt1ig1
; 1GPe9pWvvNESKs0G3eCtdtP557+5dtWqZzE/ITVO05vOumI5b7uNc+a81PSYzQbVuDpIjuWa3kwuuP
; D8iWdSq+PwbQcJlabHbDZIhgWiXB2k5EUDayj8TPhZR99mXq2GU18CEyr/9olP/O8wTUyz6Wf3nz5x
; 3fCtb4l0kJoXDawpSiN0+Bq8QXlXuvR1OzExcXj32rVP7Dn33KbHbDYltv0zn/nvzStW/BYKQmu9YO
; hbbXR09Hn0M3mkRJ6hdP60OoYBwo4Cr1rQY7YC12Z9GhaIAgZnz579OvwXMGnp6Z070cHnYh4EFhzg
; vgsXl5bQy73V6MDCL9QKXJv1YTEd5HtJvXdfBNYkIRosrBitMHkvZeqPpIRezPAuPrgzJRWUIn0ACZ
; VGHzTzNtRBrh4bO5J6ieCdI3hHq2WxwUITX3VOdwD4AtK3HeorcecoHVFbgWuzGgYFoqEOsoRBwKy0
; BRW+vQDz6mYe1GDBcRMq2AQEvrh0t2gFrs08rKSDLGEQ3nSlphzUaB6kZGwtJSwk+NDcOdfjPEwLXJ
; ses5nUrAWi72GQkVCRyh5FCw4sReilEiNaa3rMZhrT6CBLGIQ3XWzxYj2o9HNVBaiUyKOJEW9Oo+kx
; m3EM3mprPvvZtyw6yBwGaUIFME/rQXtZcGDgeMuWLY9t3br1UU5QatlpYHFv/uEPX2z0QbPQQAe5+g
; c/eNFDB1nE4ObNj42Pjz9i4alVCw7eZLDi4c0GR0wrfVAy2FHAmh6zGRrVQfaJQUyoaLWX4gUXS/d7
; VReEFgaltMC1NRyZuYaNMigG4b+9YfBd+oBDA6gXHE33p4JFTj0Q11K1eK3hyMy2sFFGiI0+MYgJFU
; nugrXgUAcJDko7iFWPyX1bQtDa9Jgzx6gOkoONvjBIEyqcRZ5dcPCFMd0vCUpT9EHJpLV4TY85MwwL
; RDXXHvSFQa5CpUutYvii2EROGyBK9Jiah0P9oB6zJVSmj2GjDNBB9oVBLbU12fTm3YRKSnUyKV6OvQ
; 4lOkjuTpMaCAahHn6aHnP6mKZRhgWDmgRICoP4tqOfh3z1ey2H4RfgC2FixPuahVgwC1/Cqs4Orekx
; h9+0OshBwiClD3AR/sOC2759++H77rvvDvjf3qlVupNgUR4tzqvhBxIqm7/znVcfbvTB0JiHDnKQML
; hu3bqnYE3t2rXrwfcWHK6+nTt3Htq7d++9Wn5BsvrHxsaOel7akvID45lYuvSZpsccfIMC0Y1LlhzR
; VJkMIgZhMYMyBTCICw5OkR2m+/EoiSblF7hfAj8T9Zg1FjaNQcFfazgyuEZ1kPT4VUsuSHWQNTBI+W
; o0XF/w3w4HRtOb9Bc9LhZKBaXo0/M6h1gM2hqODKbFGmWAaWrSONjIkdgefjAxQg3pNMTg+3g4qpOk
; CRVtpohTnAc+rVo4Ti1eazgyGIY6yFxihFuTxsVg6fgI/67FIPwNrJFwscV8RolvWFw0s0LfdtwvIS
; 3O02rhpLV4reHI1FpMB5kDsqWoWYpBfAtK/FC+moZjyZuXc4MF57G3XWkX0PYkwDtUuMGsthavFbhO
; jaEOUlq4qZFQWTDIFWFgroBayWdRSzmpWXz3DULfdjGAe1UNlLRwOYJR6qcVuNY3SIys+9KX3gDcaA
; s36cVUuRDHE4Opt2MsMcJ9A7PEy7GESni2TgWlWkvtNCih8Uofv6fH/PGPjzc9pr95NsoAAzykatK8
; +2LEFCoo5A/XAfczRfVw+GoPV/bChQv/XIvToFo4ep73vh26NRzxNdRBejfKAIPNHZMUmP22aHE52F
; iwYMHLK1eufC486Ul9qnp804QKEHsbNmx4siZZCQMGYl66m6jGdjqhcusll5xoBa5689RB5uYKa9KA
; WK6JP/hsILF37979ACcx4rrg0GCH8aQPcoPF3QTbHte8PwV2SkyotIYjckMdJDxDbeN5CTZgvqQJFQ
; kewmw9GPxM60f1hsOglKbkSwkVjR96bMCf12o4EsagqMdsBa48i+kgSyp9CzaoDlJak8YxmisIEyMW
; DIoWHBLUscGHX84imSnV4nmf2fHNmZpYKHA9cPbZjT5IWKxRRgher0t+Uo0y6CKx9ghIJQhjGJRuJp
; 3kS+Q+PJVQkaZnJbV4Vi0clxhtDUfixmmUEQLUkq7nSLCoaENKGWlObNLNpON8CS6oKVci1WOmdJAc
; n5qdRloH1fSY/2gpHWTJNJf8SAtEUUAh0WPGdJDcsUma3mQXnKRJQfhQJQkV2qxRuwNy9ZjWnXam6z
; EtjTLoAuLGQFoMop+SHjOlg9T4xKaLOQx2qS9qzTDR+/tSvIV3T4KSFi4Wg2r9jC5efHym6TFpYqSv
; aw88/KT0mFIdJBcbuaY3XfiqzgWl2sGGbztYiCMjIye15CFnIsPP9CwDomObKXpMz0YZ1GIxkFYHWf
; JD6QONDtIDgx39R0uTAs5gcWBAVB48eHD/rbfe+mQtngYTKrDIalawY0Jl5ze+cXI6JlTgrXbrhRe+
; UaNRBgUoitZrXnsAfpYvX/57wB4lsQGbNXwiBmlyb/JICc6uueaaF7xSt6nB4hETBgsGu01NnzB5o6
; Ojz3vzQDE/oLi57Uc/+tN00mNCYuSWK688nouBvAwxWFPYgLkCxB8eIWuNKYbBjnJQpfOn1TEOMJZQ
; 8fQJb016/vfkgUKQ0BgUHup00GPSRhn41rEmtUrYCDHoefKJpftxPLU2kzAGRQx24cC8SeVYYiQmmf
; FoaA6WikG9yjbQqOSMPqtJHmiIG46kCkQ9G8+nQFkDg7F0P44t7BHgiY3UdQ5JWiBXD6QBZexYh1wJ
; lz4oGScGtTZ7oJtFKqOFMcmwNRyBxAik+1PJg7AO0YqNUpLCImyIccKpdL+mwDXlsxSDdqUP0JDKlN
; sokYceekxpLZ5WCwd/J6nFG5aGI5JGGbhYtJf8SE8aGgxqCkS5Ba5WDLKkXZIYiHIb3KNHij7gnK1T
; OkjuRHL/VhvHUD3mICZUNI0yEGDSGMhSIMrFIEcHWcKvtOmiBINsLSVnZ7L2JJDoMb2I0dJEepHzg9
; ZwxKNRhiQG8qgayGHQs3KF23RRg0FxeU4sBtLqIFMPtaTH9CZGU1o47SVFOT+D0HDEu0A0FwNJdZAa
; DFp0kLm5yjVd1GJQVYBKYyDkNrzJw5gec+nSpUfnzZtXjRhFLZxFcc6xqWw4UqtRRiwGsuggORicP3
; /+X4Dj4iRGtBZuJtbWxp3li0xMTBzeunXro14XxMQeKgIfStz37Nlzn7cULDTYSJAUrVm2jwWuG2bN
; OtlHQgUSIzef9lWzUQYYbpTwDL3lWSH+1q9f/2vABGDQEsqUDN92gEFoemN5fqoFR1/h+GqtqVDBHY
; buYjXkWjQGrXkpDRgetfrQY0KBKOogPbnImCEPamk8X7JYYgTmrKYSBt/W1gJX0YKjxwa6m6RiIA9Q
; 4v0RqYSKh89UDFqr4Uh4/q91PyZtlEGfk5WLzC0E5EFLMZB1nmh8Dz61FBbHJ8VAyEVKn2EncYyDTa
; 1uTj2QBJShH1pqkUqoSK0Ug3pOZC7L9t5mNmfOSx4JlVKBqOVejthnpY6PXqRy7D7IWCjjuZnkYlAt
; F8lacBIOCh++diI5bH3sghcpWUnTyJwY1KrH5HJQWOC6/bzz3tLQB1QHWTr2eEioOBxUeMmPlMeM6S
; BzPq2bSajF5WCIy0V2kg+UPCTNREpq8Sx6TBqDSr6jVCWBJn0WtOGIRI8paZRBTbOZaDgo6SU/lgLR
; PjCIfiR6zK4ESgsHJYmBtAWiKT1mqpzeSs7jpHCOLRiDavzQAleOHhMbZWgzg5Kjs4UH5cZAXgWiUg
; xqa/64R+cufMDWoFA6kfj6t/jhqAw4MajUZ+7YIr2kKDeRkFABPeYjp5MgscQI6CC9eNDcZqJ9w6ee
; TywG0uggORjMbehSLW7OT06PCX46ev70bpQRAic8tnim3mMJFRwbEKQeE5cCIB0DJwbVji3UY3o3yq
; DACDcT70YZ6IeGLHPnzn3VooMsWazpolaLW/IT6jERm10oGq59HzwM+NJLL/1brWuwQ/oAKrHvuuuu
; A7Dj1BgTBePs2bNf9wRIzM9NY2NHbr/kkhObP//5N2s0ygjnCkFa08+11177xwMHDty5b9++e1InFC
; /DtxlevVEL6xhObNu27eEtW7Y8hptHB/+wadOmxwGY+GarSSDC58MDrllKj2Q5LjhoBOJZOBkzmLxF
; ixa9WPM6Bzzu77/99nv6IHsBG3AHiOUufQ4eYCyg4EAMwlzV7EkAC25sbOxoTWED+kH8AR4BGx3dTS
; z1QByw0PO/Jw90XgSUyK15FrimQElj0FqkchiDWmrSOEZj0FIMZJ2ncH76wmCp8afH2GAc8NwQi114
; /tfUA5Usdf734IFCP2EMmkqoePhMfXfvzSTFg2p4IA5YUjFoLAayzlMsMTIVGPTaTOBzYnkQfK7Ji2
; C9tHCcBeVxyU+uWWOqwFU7Ng4H5bGZcHhQKQ+UMw4HVbpslztPpcTIMGKQQzl1OcBYtHBSYlS709Cj
; VgksHnpMKQel1WNKeVCrhEpyZNRsJikdZM6nBwYlPKiW9pDUgxalXZqJtHBQkhiIgpJLWHIKXHOTr9
; nZJTGQhQct8UApsGiPo9yLpmIFojBGiZ9BxaC0HpSlpeRq4bw4qFIMBH5izRqlD5WbUMHvYxkT+swd
; W7x4UG4M5BE/504mdJ64OkguBnPY6AODUi0umqg8J6eFk2rQuBMZTk6pWaP0oZb0mN4cVCoGysWg1r
; GFR1qNDpKDDbqZWHSQg4bB1NUbGgyqWg6HRx7vlHH4gBEwHjrI2HhiCZUVK1YcAV6tVgUxLmRJDGoZ
; G8ZA3vfBxMb1s5/97E8bHXSQg4RBrICxYlB9xQLyQFBKX5tAhAFDAxDviQt94BEBSumx90FNIhtAg3
; 60olnu2GBRAwELMrdaJDZuHjBX9NoDT5kbNcQg+OsDg0DOW4/76gUHwAereT87+sGJQ5+1AAM7Vqz2
; yntsYQzqyQPFDOMRTgxknSfvI2TJJ4C/NgbpcR+7/Gj9iBdceP735IFCPzEOysoDpYye/0vErNVP7P
; xfq+FIKM6V1qRJ5ikUFniTyiUMer9RcxjUNr0RLThwkoozvErp0U+Op/FWqMTO/5YC15SVzv9aHogD
; ytTYLCVYuUYZITa8NpNcDOrZcKQWBkW0QCnO0PBAKSBwhLlcHqgEypwfj4YjEmIUzKrH5HJQWj1mjM
; ssxTbwN5aLprjp/nAzsWCQsxlJMVhccJriPI0WTstBaY8tkktKOQWuOT+ao45Gj6nhoKR6TGuBqOai
; KQ0PqtlM+sBgdsFZivMkWjiP8zf32KLloFL0QQqkHB2k50RaOChuDMTVQXKwwY2BrBik5DQXg9oTEw
; eDnScocyCNaeG8OahSDJSLQSUPtbTDS3WQ1on04qBSMZDlDV+aq9RiqoXBMCzqG4NdOKgaxGgsoeIN
; SmphDMSNQSUPNabHhOcGxbXcGFTqM4yBODGoxg+NYebMmfPX8K3m2W8hJu626CC1GPTmQWMYBHx0dK
; epkW6nE4n3s4+Pjz8i1aBJDc/9ANBaZHmox4SrHOCqAG/FCDWMgSQxqMZGRkZOwpUHBw8e3M9NjFiw
; 0RcGAXOAQbz2oC8MIiYmj5SwuqErTU1SGQweKLD10ICh1uRRg4d5zTXXvFCbVMYjCQAU7rDwLJyM+Q
; PpVE1gYhEljGX//v1342Kr5Q+xsWDBgpf7wCAoU7BhS22FCmIQ/XQ0KPfkgWKOabxTsx1UeP6vRSrT
; 2AbG41XgmjIag3pzkeE8UcOx1ZJp0Ri0LwyCP8RgjTtbUhjsYo6sPFDoOMVBaXmgEihTpfQWHijmJ4
; xBazUcycWg2gLX3DzRuBR9egobQlBOFQZpQgUv+bH6QmzETm/gr8t9SSkPFBqHg5LyQDlQcnZGa8MR
; qoOMFVHSFHuoUNH45PCgVgkVt1GGVdgQ+iyFFH1hEIXrmPiqicGuxkRKOSirFk56SalWCyepxfNoOC
; LloKRH55RYu+RTI2ygz15z9YbGjxaD0oYjYNzkHEvaJZlIetSSPiSNFk67s0snUlMHpdVjWjgo7pve
; WiBK43BuDGThQfvEoFTcLeFB2eLlUgzkVSDK1cJ5cVClGEiqg0wBgNtwxIsHTcVAKR2kxic3BvLiQU
; snLqkWdyowKC7PicVA4SWllocagjSWUPEmRlMTqdVBpiYnp9aokZ0LYyCrDjJluRiIE4NKLbaZeN0H
; w8WglgdVFaDSGKhGHVIMpAgcjwticsCBB0mrv73vyIjpEUdHR5+vRZbjQl62bNkfNjroIDljwxjIoo
; PkYINioi8MWitU1BXf4HhiYuIwsPY1lRVUoQKEZU3yFQzAidce1AILpQ+AXIarD2pxXAgYEBzgFQE1
; 5HR0bHj1Rk1coK9hw6BqwdGgFP63N8EbGgwW/HjzQOFDpTGotZSeA5YwrvMeW6xAtOZGgj5h07LUpA
; 0aBnHBeWCwkzqOKUSsPFDKwvO/Jw8U+onFoB48UAos6EdyP6ZmnmI6SE9SmfoMY9AawoaQBw0F6oOO
; QfaC4wSlnhKqXMrewgOFVjr/e0qoUgWiuXtBpD6497F4biY5HtRL2IDzXuIKvRqOIDa8MdhxHXPT/d
; ZsG5eD0vBAOSBwQaWdyFKBaKrAVXJUkhaIemwmnJNNWJOmwYaEcrJeNKXBIHeeutIHaovzNMcWKQel
; 1cJpa/G0R2cJB6XRY5Z0kByf0hhIw0Fp9JhaHhR5Y+lmYsEgRzf7f+CzKfIoGaa/AAAAAElFTkSuQm
; CC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.56mm


M73 P0 R3
M204 P8000 T8000 ; sets acceleration (P, T), mm/sec^2
;TYPE:Custom
M117 Initializing
; Set coordinate modes
G90 ; use absolute coordinates
M83 ; extruder relative mode
; Reset speed and extrusion rates
M220 S100 ; reset speed
; Set initial warmup temps
M117 Nozzle preheat
M104 S205 ; preheat extruder to no ooze temp
M140 S70 ; set bed temp
M190 S70 ; wait for bed final temp
; Home
M117 Homing
G28 ; home all with default mesh bed level
; Final warmup routine
M117 Final warmup
M104 S205 ; set extruder final temp
M109 S205 ; wait for extruder final temp
M190 S70 ; wait for bed final temp
BED_MESH_PROFILE LOAD=default
; Prime line routine
M117 Printing prime line
G92 E0.0; reset extrusion distance
G1 X-54.672 Y-95.203 Z0.5 F4000; go outside print area
G92 E0.0; reset extrusion distance
M73 P1 R3
G1 E2 F1000 ; de-retract and push ooze
G3 X38.904 Y-102.668 I54.672 J95.105 E20.999 F1500
G3 X54.671 Y-95.203 I-38.815 J102.373 E5.45800 F1500
G92 E0.0
G1 E-1 F3000 ; retract 1mm
G1 X52.931 Y-96.185 F1000 ; wipe
G1 X50.985 Y-97.231 F1000 ; wipe
G1 X49.018 Y-98.238 F1000 ; wipe
G1 X0 Y-109.798 F1000
G1 E1 F1500; de-retract
G92 E0.0 ; reset extrusion distance
; Final print adjustments
M117 Preparing to print
;M82 ; extruder absolute mode

M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
G92 E0 ;reset extrusion distance
G1 Z0.2 F10800
G10 ; retract
M204 S4000
G1 X26.697 Y-0.019
G11 ; unretract
;TYPE:Skirt
;WIDTH:0.52
G1 F1500
G1 X26.682 Y-20.669 E0.81917
G1 X26.447 Y-21.88 E0.04895
G1 X25.994 Y-23.028 E0.04895
M73 P2 R3
G1 X25.339 Y-24.074 E0.04895
G1 X24.508 Y-24.977 E0.04869
G1 X23.522 Y-25.718 E0.04895
G1 X22.422 Y-26.264 E0.04869
G1 X21.235 Y-26.601 E0.04895
G1 X20.006 Y-26.716 E0.04895
G1 X-20.35 Y-26.706 E1.60091
G1 X-21.695 Y-26.498 E0.054
G1 X-22.965 Y-26.026 E0.05375
G1 X-24.114 Y-25.308 E0.05375
G1 X-25.1 Y-24.369 E0.054
G1 X-25.761 Y-23.45 E0.0449
G1 X-26.257 Y-22.44 E0.04465
M73 P3 R3
G1 X-26.576 Y-21.361 E0.04465
G1 X-26.711 Y-20.243 E0.04465
G1 X-26.715 Y20.1 E1.6004
G1 X-26.543 Y21.515 E0.05653
G1 X-26.078 Y22.855 E0.05628
G1 X-25.343 Y24.069 E0.05628
G1 X-24.369 Y25.1 E0.05628
G1 X-23.45 Y25.761 E0.0449
G1 X-22.44 Y26.257 E0.04465
G1 X-21.361 Y26.576 E0.04465
G1 X-20.243 Y26.711 E0.04465
G1 X20.1 Y26.715 E1.6004
M73 P4 R3
G1 X21.515 Y26.543 E0.05653
G1 X22.855 Y26.078 E0.05628
M73 P5 R3
G1 X24.069 Y25.343 E0.05628
M73 P6 R3
G1 X25.1 Y24.369 E0.05628
G1 X25.761 Y23.45 E0.0449
G1 X26.257 Y22.44 E0.04465
G1 X26.576 Y21.361 E0.04465
G1 X26.711 Y20.237 E0.0449
G1 X26.697 Y0.041 E0.80116
M73 P7 R3
G1 X26.46 Y0.041 F10800
M204 S1000
G1 X26.223 Y0.041
G1 F1500
G1 X26.212 Y-20.58 E0.81802
G1 X25.999 Y-21.712 E0.04571
G1 X25.582 Y-22.786 E0.04571
G1 X24.978 Y-23.76 E0.04547
M73 P8 R3
G1 X24.201 Y-24.612 E0.04571
G1 X23.287 Y-25.302 E0.04547
M73 P8 R2
G1 X22.256 Y-25.817 E0.04571
G1 X21.147 Y-26.132 E0.04571
G1 X20.006 Y-26.239 E0.04547
G1 X-20.303 Y-26.231 E1.59903
G1 X-21.551 Y-26.043 E0.0501
G1 X-22.731 Y-25.609 E0.04985
G1 X-23.8 Y-24.948 E0.04985
M73 P9 R2
G1 X-24.718 Y-24.081 E0.0501
G1 X-25.341 Y-23.224 E0.04205
G1 X-25.808 Y-22.279 E0.04181
G1 X-26.109 Y-21.262 E0.04205
G1 X-26.235 Y-20.216 E0.04181
G1 X-26.238 Y20.081 E1.59854
G1 X-26.082 Y21.389 E0.05229
G1 X-25.657 Y22.631 E0.05204
G1 X-24.982 Y23.755 E0.05204
M73 P10 R2
G1 X-24.081 Y24.718 E0.05229
G1 X-23.224 Y25.341 E0.04205
G1 X-22.279 Y25.808 E0.04181
G1 X-21.262 Y26.109 E0.04205
G1 X-20.216 Y26.235 E0.04181
G1 X20.081 Y26.238 E1.59854
G1 X21.389 Y26.082 E0.05229
G1 X22.631 Y25.657 E0.05204
G1 X23.755 Y24.982 E0.05204
M73 P11 R2
G1 X24.718 Y24.081 E0.05229
G1 X25.341 Y23.224 E0.04205
G1 X25.81 Y22.273 E0.04205
G1 X26.111 Y21.256 E0.04205
G1 X26.235 Y20.21 E0.04181
G1 X26.223 Y0.101 E0.79769
G10 ; retract
M204 S4000
G1 X22.972 Y9.911 F10800
M204 S1000
G1 X19.72 Y19.72
G11 ; unretract
;TYPE:External perimeter
;WIDTH:0.56
M73 P12 R2
G1 F1500
G1 X-19.72 Y19.72 E1.69574
G1 X-19.72 Y-19.72 E1.69574
G1 X19.72 Y-19.72 E1.69574
G1 X19.72 Y19.66 E1.69316
;WIPE_START
M204 S3700
M73 P13 R2
G1 X19.374 Y19.52 F10800
;WIPE_END
G10 ; retract
M204 S4000
G1 X-0.096 Y19.115
M204 S1000
G1 X-19.565 Y18.71
G11 ; unretract
;TYPE:Solid infill
;WIDTH:0.558294
G1 F1500
G1 X-18.469 Y19.343 E0.05423
G1 X-17.435 Y19.343 E0.04433
G1 X-19.343 Y18.241 E0.09441
G1 X-19.343 Y17.644 E0.02559
G1 X-16.401 Y19.343 E0.14559
M73 P14 R2
G1 X-15.367 Y19.343 E0.04433
G1 X-19.343 Y17.047 E0.19678
G1 X-19.343 Y16.45 E0.02559
G1 X-14.333 Y19.343 E0.24797
G1 X-13.299 Y19.343 E0.04433
G1 X-19.343 Y15.853 E0.29915
G1 X-19.343 Y15.256 E0.02559
G1 X-12.264 Y19.343 E0.35034
G1 X-11.23 Y19.343 E0.04433
M73 P15 R2
G1 X-19.343 Y14.659 E0.40153
G1 X-19.343 Y14.062 E0.02559
G1 X-10.196 Y19.343 E0.45271
G1 X-9.162 Y19.343 E0.04433
G1 X-19.343 Y13.465 E0.5039
G1 X-19.343 Y12.868 E0.02559
G1 X-8.128 Y19.343 E0.55508
G1 X-7.094 Y19.343 E0.04433
G1 X-19.343 Y12.271 E0.60627
M73 P16 R2
G1 X-19.343 Y11.674 E0.02559
G1 X-6.059 Y19.343 E0.65746
G1 X-5.025 Y19.343 E0.04433
G1 X-19.343 Y11.076 E0.70864
M73 P17 R2
G1 X-19.343 Y10.479 E0.02559
M73 P18 R2
G1 X-3.991 Y19.343 E0.75983
M73 P19 R2
G1 X-2.957 Y19.343 E0.04433
M73 P20 R2
G1 X-19.343 Y9.882 E0.81101
G1 X-19.343 Y9.285 E0.02559
G1 X-1.923 Y19.343 E0.8622
G1 X-0.889 Y19.343 E0.04433
G1 X-19.343 Y8.688 E0.91339
G1 X-19.343 Y8.091 E0.02559
G1 X0.146 Y19.343 E0.96457
G1 X1.18 Y19.343 E0.04433
G1 X-19.343 Y7.494 E1.01576
G1 X-19.343 Y6.897 E0.02559
G1 X2.214 Y19.343 E1.06695
G1 X3.248 Y19.343 E0.04433
G1 X-19.343 Y6.3 E1.11813
G1 X-19.343 Y5.703 E0.02559
G1 X4.282 Y19.343 E1.16932
M73 P21 R2
G1 X5.316 Y19.343 E0.04433
G1 X-19.343 Y5.106 E1.2205
G1 X-19.343 Y4.509 E0.02559
G1 X6.35 Y19.343 E1.27169
G1 X7.385 Y19.343 E0.04433
G1 X-19.343 Y3.912 E1.32288
G1 X-19.343 Y3.315 E0.02559
G1 X8.419 Y19.343 E1.37406
M73 P22 R2
G1 X9.453 Y19.343 E0.04433
G1 X-19.343 Y2.717 E1.42525
G1 X-19.343 Y2.12 E0.02559
G1 X10.487 Y19.343 E1.47644
G1 X11.521 Y19.343 E0.04433
G1 X-19.343 Y1.523 E1.52762
M73 P23 R2
G1 X-19.343 Y0.926 E0.02559
G1 X12.555 Y19.343 E1.57881
G1 X13.59 Y19.343 E0.04433
G1 X-19.343 Y0.329 E1.62999
M73 P24 R2
G1 X-19.343 Y-0.268 E0.02559
G1 X14.624 Y19.343 E1.68118
G1 X15.658 Y19.343 E0.04433
G1 X-19.343 Y-0.865 E1.73237
M73 P25 R2
G1 X-19.343 Y-1.462 E0.02559
G1 X16.692 Y19.343 E1.78355
G1 X17.726 Y19.343 E0.04433
G1 X-19.343 Y-2.059 E1.83474
M73 P26 R2
G1 X-19.343 Y-2.656 E0.02559
G1 X18.76 Y19.343 E1.88593
G1 X19.343 Y19.343 E0.02495
G1 X19.343 Y19.082 E0.01119
M73 P27 R2
G1 X-19.343 Y-3.253 E1.91474
G1 X-19.343 Y-3.85 E0.02559
M73 P28 R2
G1 X19.343 Y18.485 E1.91474
G1 X19.343 Y17.887 E0.02559
G1 X-19.343 Y-4.447 E1.91474
G1 X-19.343 Y-5.044 E0.02559
M73 P29 R2
G1 X19.343 Y17.29 E1.91474
G1 X19.343 Y16.693 E0.02559
M73 P30 R2
G1 X-19.343 Y-5.642 E1.91474
G1 X-19.343 Y-6.239 E0.02559
M73 P31 R2
G1 X19.343 Y16.096 E1.91474
G1 X19.343 Y15.499 E0.02559
G1 X-19.343 Y-6.836 E1.91474
G1 X-19.343 Y-7.433 E0.02559
M73 P32 R2
G1 X19.343 Y14.902 E1.91474
G1 X19.343 Y14.305 E0.02559
M73 P33 R2
G1 X-19.343 Y-8.03 E1.91474
G1 X-19.343 Y-8.627 E0.02559
M73 P34 R2
G1 X19.343 Y13.708 E1.91474
G1 X19.343 Y13.111 E0.02559
M73 P35 R2
G1 X-19.343 Y-9.224 E1.91474
G1 X-19.343 Y-9.821 E0.02559
M73 P36 R2
G1 X19.343 Y12.514 E1.91474
G1 X19.343 Y11.917 E0.02559
M73 P37 R2
G1 X-19.343 Y-10.418 E1.91474
G1 X-19.343 Y-11.015 E0.02559
M73 P38 R2
G1 X19.343 Y11.32 E1.91474
G1 X19.343 Y10.723 E0.02559
M73 P39 R2
G1 X-19.343 Y-11.612 E1.91474
G1 X-19.343 Y-12.209 E0.02559
M73 P40 R2
G1 X19.343 Y10.126 E1.91474
G1 X19.343 Y9.528 E0.02559
M73 P41 R2
G1 X-19.343 Y-12.806 E1.91474
G1 X-19.343 Y-13.403 E0.02559
G1 X19.343 Y8.931 E1.91474
M73 P42 R2
G1 X19.343 Y8.334 E0.02559
G1 X-19.343 Y-14.001 E1.91474
M73 P43 R2
G1 X-19.343 Y-14.598 E0.02559
G1 X19.343 Y7.737 E1.91474
M73 P44 R2
G1 X19.343 Y7.14 E0.02559
G1 X-19.343 Y-15.195 E1.91474
M73 P45 R1
G1 X-19.343 Y-15.792 E0.02559
G1 X19.343 Y6.543 E1.91474
M73 P47 R1
G1 X19.343 Y5.946 E0.02559
G1 X-19.343 Y-16.389 E1.91474
M73 P48 R1
G1 X-19.343 Y-16.986 E0.02559
G1 X19.343 Y5.349 E1.91474
M73 P49 R1
G1 X19.343 Y4.752 E0.02559
G1 X-19.343 Y-17.583 E1.91474
M73 P50 R1
G1 X-19.343 Y-18.18 E0.02559
G1 X19.343 Y4.155 E1.91474
M73 P51 R1
G1 X19.343 Y3.558 E0.02559
G1 X-19.343 Y-18.777 E1.91474
M73 P52 R1
G1 X-19.343 Y-19.343 E0.02424
G1 X-19.288 Y-19.343 E0.00235
M73 P53 R1
G1 X19.343 Y2.961 E1.91203
G1 X19.343 Y2.364 E0.02559
M73 P54 R1
G1 X-18.254 Y-19.343 E1.86084
G1 X-17.219 Y-19.343 E0.04433
M73 P55 R1
G1 X19.343 Y1.767 E1.80966
G1 X19.343 Y1.169 E0.02559
M73 P57 R1
G1 X-16.185 Y-19.343 E1.75847
G1 X-15.151 Y-19.343 E0.04433
M73 P58 R1
G1 X19.343 Y0.572 E1.70728
G1 X19.343 Y-0.025 E0.02559
M73 P59 R1
G1 X-14.117 Y-19.343 E1.6561
G1 X-13.083 Y-19.343 E0.04433
M73 P60 R1
G1 X19.343 Y-0.622 E1.60491
G1 X19.343 Y-1.219 E0.02559
M73 P61 R1
G1 X-12.049 Y-19.343 E1.55372
G1 X-11.014 Y-19.343 E0.04433
M73 P62 R1
G1 X19.343 Y-1.816 E1.50254
G1 X19.343 Y-2.413 E0.02559
M73 P63 R1
G1 X-9.98 Y-19.343 E1.45135
G1 X-8.946 Y-19.343 E0.04433
M73 P64 R1
G1 X19.343 Y-3.01 E1.40017
G1 X19.343 Y-3.607 E0.02559
M73 P65 R1
G1 X-7.912 Y-19.343 E1.34898
G1 X-6.878 Y-19.343 E0.04433
M73 P67 R1
G1 X19.343 Y-4.204 E1.29779
G1 X19.343 Y-4.801 E0.02559
M73 P68 R1
G1 X-5.844 Y-19.343 E1.24661
G1 X-4.81 Y-19.343 E0.04433
M73 P69 R1
G1 X19.343 Y-5.398 E1.19542
G1 X19.343 Y-5.995 E0.02559
M73 P70 R1
G1 X-3.775 Y-19.343 E1.14424
G1 X-2.741 Y-19.343 E0.04433
M73 P71 R1
G1 X19.343 Y-6.592 E1.09305
G1 X19.343 Y-7.19 E0.02559
G1 X-1.707 Y-19.343 E1.04186
M73 P72 R1
G1 X-0.673 Y-19.343 E0.04433
G1 X19.343 Y-7.787 E0.99068
M73 P73 R1
G1 X19.343 Y-8.384 E0.02559
G1 X0.361 Y-19.343 E0.93949
M73 P74 R1
G1 X1.395 Y-19.343 E0.04433
G1 X19.343 Y-8.981 E0.8883
M73 P75 R1
G1 X19.343 Y-9.578 E0.02559
G1 X2.43 Y-19.343 E0.83712
M73 P76 R1
G1 X3.464 Y-19.343 E0.04433
G1 X19.343 Y-10.175 E0.78593
M73 P77 R1
G1 X19.343 Y-10.772 E0.02559
G1 X4.498 Y-19.343 E0.73475
M73 P78 R1
G1 X5.532 Y-19.343 E0.04433
G1 X19.343 Y-11.369 E0.68356
M73 P79 R1
G1 X19.343 Y-11.966 E0.02559
G1 X6.566 Y-19.343 E0.63237
M73 P80 R1
G1 X7.6 Y-19.343 E0.04433
G1 X19.343 Y-12.563 E0.58119
M73 P81 R1
G1 X19.343 Y-13.16 E0.02559
G1 X8.635 Y-19.343 E0.53
M73 P82 R0
G1 X9.669 Y-19.343 E0.04433
G1 X19.343 Y-13.757 E0.47881
G1 X19.343 Y-14.354 E0.02559
G1 X10.703 Y-19.343 E0.42763
M73 P83 R0
G1 X11.737 Y-19.343 E0.04433
G1 X19.343 Y-14.951 E0.37644
M73 P84 R0
G1 X19.343 Y-15.549 E0.02559
G1 X12.771 Y-19.343 E0.32526
M73 P85 R0
G1 X13.805 Y-19.343 E0.04433
G1 X19.343 Y-16.146 E0.27407
G1 X19.343 Y-16.743 E0.02559
G1 X14.839 Y-19.343 E0.22288
M73 P86 R0
G1 X15.874 Y-19.343 E0.04433
G1 X19.343 Y-17.34 E0.1717
G1 X19.343 Y-17.937 E0.02559
M73 P87 R0
G1 X16.908 Y-19.343 E0.12051
G1 X17.942 Y-19.343 E0.04433
G1 X19.343 Y-18.534 E0.06932
M73 P88 R0
G1 X19.343 Y-19.131 E0.02559
G1 X18.591 Y-19.565 E0.0372
G10 ; retract
;TYPE:Custom
; printing object ENDGCODE
G92 E0.0 ; prepare to retract
G1 E-1 F3000; retract to avoid stringing
; Anti-stringing end wiggle
G1 Z100.2 F4000 ; Move print head up
M73 P89 R0
G1 X0 Y120 F3000 ; present print
; Reset print setting overrides
G92 E0
M220 S100 ; reset speed factor to 100%
; Shut down printer
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M18 S180 ;disable motors after 180s
Super_racer ;reset to super racer defaults 
M117 Print finish.
M73 P100 R0
; filament used [mm] = 150.06
; filament used [cm3] = 0.36
; filament used [g] = 0.45
; filament cost = 0.01
; total filament used [g] = 0.45
; total filament cost = 0.01
; total layers count = 1
; estimated printing time (normal mode) = 2m 43s

; allow_empty_layers = 0
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 1
; avoid_crossing_perimeters_max_detour = 8
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 129.505x11.3302,128.025x22.5743,125.57x33.6465,122.16x44.4626,117.82x54.9404,112.583x65,106.49x74.5649,99.5858x83.5624,91.9239x91.9239,83.5624x99.5858,74.5649x106.49,65x112.583,54.9404x117.82,44.4626x122.16,33.6465x125.57,22.5743x128.025,11.3302x129.505,7.9602e-15x130,-11.3302x129.505,-22.5743x128.025,-33.6465x125.57,-44.4626x122.16,-54.9404x117.82,-65x112.583,-74.5649x106.49,-83.5624x99.5858,-91.9239x91.9239,-99.5858x83.5624,-106.49x74.5649,-112.583x65,-117.82x54.9404,-122.16x44.4626,-125.57x33.6465,-128.025x22.5743,-129.505x11.3302,-130x1.59204e-14,-129.505x-11.3302,-128.025x-22.5743,-125.57x-33.6465,-122.16x-44.4626,-117.82x-54.9404,-112.583x-65,-106.49x-74.5649,-99.5858x-83.5624,-91.9239x-91.9239,-83.5624x-99.5858,-74.5649x-106.49,-65x-112.583,-54.9404x-117.82,-44.4626x-122.16,-33.6465x-125.57,-22.5743x-128.025,-11.3302x-129.505,-2.38806e-14x-130,11.3302x-129.505,22.5743x-128.025,33.6465x-125.57,44.4626x-122.16,54.9404x-117.82,65x-112.583,74.5649x-106.49,83.5624x-99.5858,91.9239x-91.9239,99.5858x-83.5624,106.49x-74.5649,112.583x-65,117.82x-54.9404,122.16x-44.4626,125.57x-33.6465,128.025x-22.5743,129.505x-11.3302,130x-3.18408e-14
; bed_temperature = 65
; before_layer_gcode = G92 E0 ;reset extrusion distance
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0.8
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 100%
; bridge_internal_fan_speed = -1
; bridge_overlap = 90%
; bridge_overlap_min = 80%
; bridge_speed = 60
; bridge_speed_internal = 150%
; bridged_infill_margin = 200%
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_offset = 0
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 15
; clip_multipart_objects = 1
; color_change_gcode = M600
; complete_objects = 0
; complete_objects_one_brim = 0
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; curve_smoothing_angle_concave = 0
; curve_smoothing_angle_convex = 0
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 3700
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = 0
; duplicate_distance = 6
; end_filament_gcode = ""
; end_gcode = ; printing object ENDGCODE\nG92 E0.0 ; prepare to retract\nG1 E-1 F3000; retract to avoid stringing\n; Anti-stringing end wiggle\n{if layer_z < max_print_height}G1 Z{min(layer_z+100, max_print_height)}{endif} F4000 ; Move print head up\nG1 X0 Y120 F3000 ; present print\n; Reset print setting overrides\nG92 E0\nM220 S100 ; reset speed factor to 100%\n; Shut down printer\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM18 S180 ;disable motors after 180s\nSuper_racer ;reset to super racer defaults \nM117 Print finish.\n
; enforce_full_fill_volume = 1
; ensure_vertical_shell_thickness = 0
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_cut_corners = 0%
; external_perimeter_extrusion_spacing = 
; external_perimeter_extrusion_width = 0.45
; external_perimeter_fan_speed = -1
; external_perimeter_overlap = 100%
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_fan_offset = 0%
; extruder_offset = 0x0
; extruder_temperature_offset = 0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_spacing = 
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; fan_kickstart = 0
; fan_percentage = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; feature_gcode = 
; filament_colour = #FF3232
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cooling_zone_pause = 0
; filament_cost = 20
; filament_custom_variables = ""
; filament_density = 1.24
; filament_diameter = 1.75
; filament_dip_extraction_speed = 70
; filament_dip_insertion_speed = 33
; filament_enable_toolchange_part_fan = 0
; filament_enable_toolchange_temp = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_overlap = 100%
; filament_max_speed = 0
; filament_max_volumetric_speed = 64
; filament_max_wipe_tower_speed = 0
; filament_melt_zone_pause = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Basic PLA @VORON - Copy"
; filament_shrink = 100%
; filament_skinnydip_distance = 31
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_toolchange_part_fan_speed = 50
; filament_toolchange_temp = 200
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_use_fast_skinnydip = 0
; filament_use_skinnydip = 0
; filament_vendor = (Unknown)
; filament_wipe_advanced_pigment = 0.5
; fill_angle = 210
; fill_angle_increment = 0
; fill_density = 20%
; fill_pattern = gyroid
; fill_smooth_distribution = 10%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 100%
; first_layer_acceleration = 1000
; first_layer_bed_temperature = 70
; first_layer_extrusion_spacing = 
; first_layer_extrusion_width = 140%
; first_layer_flow_ratio = 100%
; first_layer_height = 0.2
; first_layer_infill_speed = 25
; first_layer_min_speed = 25
; first_layer_size_compensation = 0
; first_layer_size_compensation_layers = 1
; first_layer_speed = 25
; first_layer_temperature = 205
; full_fan_speed_layer = 4
; gap_fill = 1
; gap_fill_last = 0
; gap_fill_min_area = 100%
; gap_fill_overlap = 100%
; gap_fill_speed = 31
; gcode_comments = 0
; gcode_filename_illegal_char = 
; gcode_flavor = klipper
; gcode_label_objects = 0
; gcode_precision_e = 5
; gcode_precision_xyz = 3
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; infill_acceleration = 3700
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_connection = connected
; infill_connection_bottom = connected
; infill_connection_solid = connected
; infill_connection_top = connected
; infill_dense = 0
; infill_dense_algo = autoenlarged
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_spacing = 
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 150
; interface_shells = 0
; ironing = 0
; ironing_angle = -1
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.2
; lift_min = 0
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 3700,5000
; machine_max_acceleration_extruding = 8000,1250
; machine_max_acceleration_retracting = 8000,1250
; machine_max_acceleration_travel = 8000,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 3700,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 31,10
; machine_max_jerk_y = 31,10
; machine_max_jerk_z = 31,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_gcode_per_second = 1500
; max_layer_height = 0.35
; max_print_height = 310
; max_print_speed = 150
; max_speed_reduction = 90%
; max_volumetric_speed = 17
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode = 
; milling_toolchange_start_gcode = 
; min_fan_speed = 100
; min_layer_height = 0.05
; min_length = 0.035
; min_print_speed = 15
; min_skirt_length = 0
; min_width_top_surface = 200%
; model_precision = 0.0001
; no_perimeter_unsupported_algo = none
; notes = 
; nozzle_diameter = 0.4
; only_one_perimeter_first_layer = 0
; only_one_perimeter_top = 1
; only_one_perimeter_top_other_algo = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_flow_ratio = 100%
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 100%
; overhangs_width = 75%
; overhangs_width_speed = 50%
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 2800
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_spacing = 
; perimeter_extrusion_width = 0.45
; perimeter_loop = 0
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_round_corners = 0
; perimeter_speed = 133
; perimeters = 3
; physical_printer_settings_id = Flsun Sr Klipper
; post_process = 
; print_custom_variables = 
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = Super Racer
; print_temperature = 0
; printer_custom_variables = 
; printer_model = 
; printer_notes = 
; printer_settings_id = Super Racer
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_layers = 0
; remaining_times = 1
; remaining_times_type = m73
; resolution = 0.0125
; resolution_internal = 0.2
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_lift_first_layer = 0
; retract_lift_top = "All surfaces"
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_angle_cost = 80%
; seam_gap = 15%
; seam_position = aligned
; seam_travel_cost = 20%
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_brim = 0
; skirt_distance = 6
; skirt_distance_from_brim = 1
; skirt_extrusion_width = 130%
; skirt_height = 1
; skirts = 2
; slice_closing_radius = 0.049
; slowdown_below_layer_time = 1
; small_perimeter_max_length = 20
; small_perimeter_min_length = 6
; small_perimeter_speed = 60
; solid_fill_pattern = rectilineargapfill
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_spacing = 
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 75
; solid_over_perimeters = 2
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = ""
; start_gcode = ;STARTGCODE\nSuper_racer ;call macro set voron mode \nM117 Initializing\n; Set coordinate modes\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\n; Reset speed and extrusion rates\nM220 S100 ; reset speed\n; Set initial warmup temps\nM117 Nozzle preheat\nM104 S205 ; preheat extruder to no ooze temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed final temp\n; Home\nM117 Homing\nG28 ; home all with default mesh bed level\n; Final warmup routine\nM117 Final warmup\nM104 S[first_layer_temperature] ; set extruder final temp\nM109 S[first_layer_temperature] ; wait for extruder final temp\nM190 S[first_layer_bed_temperature] ; wait for bed final temp\nBED_MESH_PROFILE LOAD=default\n; Prime line routine\nM117 Printing prime line\nG92 E0.0; reset extrusion distance\nG1 X-54.672 Y-95.203 Z0.5 F4000; go outside print area\nG92 E0.0; reset extrusion distance\nG1 E2 F1000 ; de-retract and push ooze\nG3 X38.904 Y-102.668 I54.672 J95.105 E20.999 F1500\nG3 X54.671 Y-95.203 I-38.815 J102.373 E5.45800 F1500\nG92 E0.0\nG1 E-1 F3000 ; retract 1mm\nG1 X52.931 Y-96.185 F1000 ; wipe\nG1 X50.985 Y-97.231 F1000 ; wipe\nG1 X49.018 Y-98.238 F1000 ; wipe\nG1 X0 Y-109.798 F1000\nG1 E1 F1500; de-retract\nG92 E0.0 ; reset extrusion distance\n; Final print adjustments\nM117 Preparing to print\n;M82 ; extruder absolute mode\n\n
; start_gcode_manual = 0
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_buildplate_only = 0
; support_material_contact_distance_bottom = 0.2
; support_material_contact_distance_top = 0.2
; support_material_contact_distance_type = plane
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_solid_first_layer = 0
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; temperature = 205
; template_custom_gcode = 
; thin_perimeters = 1
; thin_perimeters_all = 0
; thin_walls = 1
; thin_walls_merge = 1
; thin_walls_min_width = 33%
; thin_walls_overlap = 50%
; thin_walls_speed = 30
; threads = 8
; thumbnails = 16x16,220x220
; thumbnails_color = #018aff
; thumbnails_custom_color = 0
; thumbnails_end_file = 0
; thumbnails_with_bed = 1
; time_estimation_compensation = 100%
; tool_name = ""
; toolchange_gcode = 
; top_fan_speed = 100
; top_fill_pattern = monotonic
; top_infill_extrusion_spacing = 
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 45
; top_solid_layers = 3
; top_solid_min_thickness = 0.8
; travel_acceleration = 4000
; travel_speed = 180
; travel_speed_z = 0
; use_firmware_retraction = 1
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 0
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_only_crossing = 1
; wipe_speed = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim = 150%
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 180
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0
; z_offset = 0
; z_step = 0.005
